### PR TITLE
Change move destination

### PR DESCRIPTION
**Pull request by moshes-next**
Move directories as is.
Move files to a directory named with the file timestamp

### CODE REVIEW

**Review by oryanpeer — APPROVED** [review]

**Review by moshebs — COMMENTED** [review]
@moshes-next when do we expect directories in the folder?

**Comment by oryanpeer** [comment]
@moshebs  - It will be passed from the pipeline as a variable

**Comment by moshebs** [comment]
> @moshebs - It will be passed from the pipeline as a variable

@oryanpeer what will be passed as a parameter?

**Comment by oryanpeer** [comment]
@moshebs - the variable will be an export path for the heap dump.

**Comment by moshebs** [comment]
> @moshebs - the variable will be an export path for the heap dump.

Ah, thanks, @oryanpeer.

Not sure if you guys are aware and want to handle at some point, but I think there might be cases where the dump collector is trying to move the file before it is ready and then bad things might happen

**Comment by oryanpeer** [comment]
@moshes-next - FYI, please review @moshebs comment.

**Comment by moshes-next** [comment]
> > @moshebs - the variable will be an export path for the heap dump.
> 
> Ah, thanks, @oryanpeer.
> 
> Not sure if you guys are aware and want to handle at some point, but I think there might be cases where the dump collector is trying to move the file before it is ready and then bad things might happen

This might be, but it's unrelated to this change

**Review by zvikad1 — APPROVED** [review]

**Pull request merged**
